### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by balupton** [rstacruz/tinkerbin#13]
What is the license? As I'm planning to revamp it using the docpad rendering engine.

https://github.com/balupton/docpad

**Comment by rstacruz** [comment]
Oops, I didn't put it did I? Go on ahead. Assume it's MIT, I'll put it in the readme soon.

Also, I'd love to see what you have planned!

**Comment by balupton** [comment]
Champion.

On the note of the tinkerbin to docpad port, I started work on that and ended up creating https://github.com/balupton/canvas.docpad which serves more or less the exact purpose that I was planning to accomplish with a tinkerbin to docpad port. However, much simpler and more powerful (naturally, as we are using your favourite text editor and docpad straight up).

Would love to know your thoughts! :-) Could do with a nice youtube video to explain what it is, and the power it gives you.
